One hundred small files in parallel for echo4 port 1819 size 1000:
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m3,641s
user	0m0,024s
sys	0m0,027s
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m4,594s
user	0m0,020s
sys	0m0,020s
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m3,756s
user	0m0,032s
sys	0m0,035s

real	0m4,880s
user	0m0,034s
sys	0m0,020s
Exception in thread Thread-1 (Rdr):
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m6,585s
user	0m0,028s
sys	0m0,017s

real	0m6,444s
user	0m0,023s
sys	0m0,015s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m6,741s
user	0m0,017s
sys	0m0,034s

real	0m6,752s
user	0m0,034s
sys	0m0,012s

real	0m6,059s
user	0m0,027s
sys	0m0,014s

real	0m6,831s
user	0m0,023s
sys	0m0,034s

real	0m6,087s
user	0m0,027s
sys	0m0,021s

real	0m7,019s
user	0m0,021s
sys	0m0,019s

real	0m6,560s
user	0m0,042s
sys	0m0,026s

real	0m7,140s
user	0m0,042s
sys	0m0,019s

real	0m6,122s
user	0m0,032s
sys	0m0,036s

real	0m7,473s
user	0m0,029s
sys	0m0,007s

real	0m6,850s
user	0m0,049s
sys	0m0,040s

real	0m6,965s
user	0m0,023s
sys	0m0,034s

real	0m7,716s
user	0m0,012s
sys	0m0,034s

real	0m8,436s
user	0m0,036s
sys	0m0,016s

real	0m7,708s
user	0m0,017s
sys	0m0,021s

real	0m8,628s
user	0m0,037s
sys	0m0,012s

real	0m7,741s
user	0m0,025s
sys	0m0,033s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
BrokenPipeError: [Errno 32] Broken pipe

real	0m8,990s
user	0m0,016s
sys	0m0,032s

real	0m8,524s
user	0m0,021s
sys	0m0,046s

real	0m8,545s
user	0m0,026s
sys	0m0,018s

real	0m8,181s
user	0m0,037s
sys	0m0,022s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m9,567s
user	0m0,035s
sys	0m0,024s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m9,967s
user	0m0,041s
sys	0m0,023s

real	0m9,927s
user	0m0,024s
sys	0m0,028s

real	0m9,979s
user	0m0,028s
sys	0m0,018s

real	0m10,072s
user	0m0,039s
sys	0m0,058s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m10,256s
user	0m0,041s
sys	0m0,067s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m10,413s
user	0m0,041s
sys	0m0,005s

real	0m10,731s
user	0m0,038s
sys	0m0,000s

real	0m10,842s
user	0m0,025s
sys	0m0,016s

real	0m10,950s
user	0m0,023s
sys	0m0,022s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m11,040s
user	0m0,008s
sys	0m0,036s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
BrokenPipeError: [Errno 32] Broken pipe

real	0m11,259s
user	0m0,022s
sys	0m0,048s

real	0m11,274s
user	0m0,025s
sys	0m0,034s

real	0m11,335s
user	0m0,023s
sys	0m0,032s

real	0m11,461s
user	0m0,025s
sys	0m0,034s

real	0m11,534s
user	0m0,024s
sys	0m0,065s

real	0m11,705s
user	0m0,011s
sys	0m0,064s

real	0m11,659s
user	0m0,033s
sys	0m0,035s

real	0m11,212s
user	0m0,023s
sys	0m0,029s

real	0m11,324s
user	0m0,021s
sys	0m0,021s

real	0m12,112s
user	0m0,039s
sys	0m0,054s

real	0m12,381s
user	0m0,030s
sys	0m0,024s

real	0m11,110s
user	0m0,021s
sys	0m0,021s

real	0m12,631s
user	0m0,028s
sys	0m0,011s

real	0m11,929s
user	0m0,011s
sys	0m0,030s

real	0m11,860s
user	0m0,009s
sys	0m0,046s

real	0m12,082s
user	0m0,022s
sys	0m0,021s

real	0m13,061s
user	0m0,029s
sys	0m0,066s

real	0m12,693s
user	0m0,030s
sys	0m0,029s

real	0m13,138s
user	0m0,043s
sys	0m0,075s

real	0m13,149s
user	0m0,024s
sys	0m0,030s

real	0m12,752s
user	0m0,033s
sys	0m0,021s

real	0m13,044s
user	0m0,025s
sys	0m0,019s

real	0m12,933s
user	0m0,029s
sys	0m0,040s

real	0m12,849s
user	0m0,022s
sys	0m0,025s

real	0m12,117s
user	0m0,040s
sys	0m0,035s

real	0m12,273s
user	0m0,031s
sys	0m0,050s

real	0m13,438s
user	0m0,027s
sys	0m0,044s

real	0m13,705s
user	0m0,017s
sys	0m0,067s

real	0m13,502s
user	0m0,032s
sys	0m0,014s

real	0m13,325s
user	0m0,017s
sys	0m0,029s

real	0m12,894s
user	0m0,028s
sys	0m0,012s

real	0m14,091s
user	0m0,025s
sys	0m0,023s

real	0m13,676s
user	0m0,022s
sys	0m0,017s

real	0m13,070s
user	0m0,034s
sys	0m0,029s

real	0m12,969s
user	0m0,036s
sys	0m0,011s

real	0m13,079s
user	0m0,029s
sys	0m0,024s

real	0m14,204s
user	0m0,027s
sys	0m0,023s

real	0m13,029s
user	0m0,036s
sys	0m0,044s

real	0m14,377s
user	0m0,043s
sys	0m0,039s

real	0m12,921s
user	0m0,030s
sys	0m0,041s

real	0m13,602s
user	0m0,035s
sys	0m0,025s

real	0m13,374s
user	0m0,035s
sys	0m0,022s

real	0m14,527s
user	0m0,033s
sys	0m0,029s

real	0m14,609s
user	0m0,042s
sys	0m0,063s

real	0m14,695s
user	0m0,027s
sys	0m0,066s

real	0m19,063s
user	0m0,022s
sys	0m0,033s

real	0m20,609s
user	0m0,021s
sys	0m0,053s

real	0m19,302s
user	0m0,020s
sys	0m0,059s

real	0m19,725s
user	0m0,025s
sys	0m0,044s

real	0m20,726s
user	0m0,028s
sys	0m0,078s

real	0m20,708s
user	0m0,052s
sys	0m0,055s

real	0m20,271s
user	0m0,031s
sys	0m0,010s

real	0m20,287s
user	0m0,030s
sys	0m0,030s

real	0m21,624s
user	0m0,019s
sys	0m0,044s

real	0m20,582s
user	0m0,019s
sys	0m0,042s

real	0m20,463s
user	0m0,035s
sys	0m0,034s

real	0m20,721s
user	0m0,016s
sys	0m0,031s

real	0m22,016s
user	0m0,018s
sys	0m0,035s

real	0m21,966s
user	0m0,027s
sys	0m0,016s

real	0m20,898s
user	0m0,037s
sys	0m0,028s

real	0m21,052s
user	0m0,019s
sys	0m0,060s

real	0m22,030s
user	0m0,027s
sys	0m0,047s
