One hundred small files in parallel for echo4 port 1819 size 2000:
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m2,854s
user	0m0,029s
sys	0m0,021s
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m2,587s
user	0m0,036s
sys	0m0,019s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m3,963s
user	0m0,029s
sys	0m0,008s
    s.send(chunk)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m2,863s
user	0m0,018s
sys	0m0,026s
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m3,731s
user	0m0,012s
sys	0m0,037s

real	0m3,706s
user	0m0,022s
sys	0m0,022s

real	0m4,427s
user	0m0,027s
sys	0m0,017s
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m3,556s
user	0m0,030s
sys	0m0,029s
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m3,616s
user	0m0,029s
sys	0m0,011s

real	0m5,970s
user	0m0,021s
sys	0m0,025s

real	0m6,213s
user	0m0,032s
sys	0m0,023s

real	0m5,120s
user	0m0,041s
sys	0m0,000s
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m6,479s
user	0m0,024s
sys	0m0,036s

real	0m6,479s
user	0m0,023s
sys	0m0,026s

real	0m6,302s
user	0m0,044s
sys	0m0,000s

real	0m6,009s
user	0m0,017s
sys	0m0,026s

real	0m5,671s
user	0m0,042s
sys	0m0,007s

real	0m5,716s
user	0m0,034s
sys	0m0,011s

real	0m6,566s
user	0m0,014s
sys	0m0,044s

real	0m6,789s
user	0m0,036s
sys	0m0,015s

real	0m6,595s
user	0m0,027s
sys	0m0,040s

real	0m6,579s
user	0m0,015s
sys	0m0,038s

real	0m5,973s
user	0m0,018s
sys	0m0,039s

real	0m6,141s
user	0m0,035s
sys	0m0,038s

real	0m7,402s
user	0m0,017s
sys	0m0,034s

real	0m6,575s
user	0m0,034s
sys	0m0,023s

real	0m6,837s
user	0m0,041s
sys	0m0,026s

real	0m7,005s
user	0m0,031s
sys	0m0,038s

real	0m7,629s
user	0m0,063s
sys	0m0,034s

real	0m8,577s
user	0m0,047s
sys	0m0,008s

real	0m7,972s
user	0m0,034s
sys	0m0,039s

real	0m7,036s
user	0m0,056s
sys	0m0,035s

real	0m6,856s
user	0m0,051s
sys	0m0,027s

real	0m8,983s
user	0m0,016s
sys	0m0,047s

real	0m9,255s
user	0m0,023s
sys	0m0,032s

real	0m9,471s
user	0m0,018s
sys	0m0,036s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

real	0m10,046s
user	0m0,030s
sys	0m0,029s

real	0m10,061s
user	0m0,024s
sys	0m0,084s
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m9,569s
user	0m0,030s
sys	0m0,024s

real	0m10,150s
user	0m0,020s
sys	0m0,058s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m9,097s
user	0m0,027s
sys	0m0,027s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m9,748s
user	0m0,019s
sys	0m0,038s
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>

real	0m10,076s
user	0m0,027s
sys	0m0,032s
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m10,357s
user	0m0,014s
sys	0m0,024s
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m10,747s
user	0m0,033s
sys	0m0,010s

real	0m10,865s
user	0m0,020s
sys	0m0,047s

real	0m10,655s
user	0m0,026s
sys	0m0,026s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m9,550s
user	0m0,026s
sys	0m0,029s

real	0m10,983s
user	0m0,027s
sys	0m0,013s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 46, in <module>
    s.send(chunk)
ConnectionResetError: [Errno 104] Connection reset by peer
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m9,931s
user	0m0,049s
sys	0m0,018s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m11,097s
user	0m0,022s
sys	0m0,022s

real	0m10,567s
user	0m0,017s
sys	0m0,067s

real	0m11,655s
user	0m0,033s
sys	0m0,013s

real	0m11,591s
user	0m0,028s
sys	0m0,022s

real	0m12,192s
user	0m0,034s
sys	0m0,011s

real	0m13,015s
user	0m0,029s
sys	0m0,017s

real	0m12,985s
user	0m0,000s
sys	0m0,041s

real	0m12,744s
user	0m0,023s
sys	0m0,030s

real	0m13,191s
user	0m0,024s
sys	0m0,030s

real	0m12,141s
user	0m0,023s
sys	0m0,018s

real	0m13,682s
user	0m0,036s
sys	0m0,009s

real	0m13,462s
user	0m0,042s
sys	0m0,000s

real	0m13,548s
user	0m0,016s
sys	0m0,026s

real	0m13,692s
user	0m0,034s
sys	0m0,039s

real	0m13,785s
user	0m0,033s
sys	0m0,007s

real	0m13,843s
user	0m0,042s
sys	0m0,026s

real	0m13,756s
user	0m0,023s
sys	0m0,027s

real	0m14,007s
user	0m0,031s
sys	0m0,118s

real	0m13,774s
user	0m0,030s
sys	0m0,020s

real	0m12,629s
user	0m0,042s
sys	0m0,012s

real	0m14,146s
user	0m0,025s
sys	0m0,014s

real	0m14,270s
user	0m0,024s
sys	0m0,039s

real	0m14,445s
user	0m0,033s
sys	0m0,035s

real	0m13,015s
user	0m0,034s
sys	0m0,048s

real	0m14,318s
user	0m0,039s
sys	0m0,035s

real	0m14,352s
user	0m0,007s
sys	0m0,041s

real	0m14,641s
user	0m0,017s
sys	0m0,042s

real	0m14,664s
user	0m0,030s
sys	0m0,020s

real	0m14,600s
user	0m0,023s
sys	0m0,029s

real	0m13,920s
user	0m0,024s
sys	0m0,052s

real	0m14,924s
user	0m0,025s
sys	0m0,025s

real	0m14,752s
user	0m0,029s
sys	0m0,018s

real	0m14,859s
user	0m0,026s
sys	0m0,026s

real	0m14,490s
user	0m0,057s
sys	0m0,088s

real	0m20,118s
user	0m0,016s
sys	0m0,060s

real	0m20,157s
user	0m0,009s
sys	0m0,044s

real	0m21,006s
user	0m0,024s
sys	0m0,072s

real	0m21,546s
user	0m0,022s
sys	0m0,112s

real	0m20,624s
user	0m0,026s
sys	0m0,052s

real	0m20,786s
user	0m0,021s
sys	0m0,059s

real	0m20,560s
user	0m0,013s
sys	0m0,052s

real	0m21,960s
user	0m0,026s
sys	0m0,085s

real	0m23,143s
user	0m0,024s
sys	0m0,133s

real	0m36,092s
user	0m0,023s
sys	0m0,037s

real	0m37,146s
user	0m0,015s
sys	0m0,040s

real	0m36,537s
user	0m0,033s
sys	0m0,033s

real	0m36,544s
user	0m0,029s
sys	0m0,035s

real	0m36,836s
user	0m0,037s
sys	0m0,031s

real	0m35,928s
user	0m0,033s
sys	0m0,062s

real	0m37,251s
user	0m0,039s
sys	0m0,045s
